export const GET_DATA = 'GET_DATA';
export const SET_FIELD_SUDOKU = 'SET_FIELD_SUDOKU';
export const CLEAR_FIELD_SUDOKU = 'CLEAR_FIELD_SUDOKU';
export const GET_VALUE = 'GET_VALUE';
export const UPDATE_SUDOKU = 'UPDATE_SUDOKU';
export const SET_OPTION = 'SET_OPTION';
export const SET_ITERATION_LIMIT='ITERATION_LIMIT';
